### PR TITLE
Fix dependencies and empty window on linux

### PR DESCRIPTION
**Pull request by feldim2425**
Is tried using dManager with wine on Ubuntu but it only produced a white window, after that I found the repo and tried to build it myself but it seems like some dependencies are not the right version or missing so the build constantly failed. After I fixed the dependencies I noticed that the Electron window is still empty and in the Dev Tools from Electron it showed some error messages  caused by an error in "app.component.ts" seems like it only effects linux since it doesn't define a appData variable, and the fallback had a small typo. Thats also fixed now.

### CODE REVIEW

**Comment by Minenash** [comment]
How did you get it to allow it to run at all. When I tried using wine, dManager just told me I had to have Windows 7 or higher? I did download from the site, though.

**Comment by feldim2425** [comment]
Well first things first, in the wine configuration menu you can change the "emulated" windows version. Second: I didn't run the official windows download on my Ubuntu PC, I compiled it myself.
You can get the AppImage or the unpacked version for linux on the my forked repo unter releases (https://github.com/feldim2425/dManager/releases) or compile / build it yourseld.
To build it you have to download / clone the repo (my forked version, the original won't work) to your PC (make sure NodeJS and NPM is installed) and run the following commands: 
   
> npm install

> npm run electron:linux

This will build the source code and put the compiled version into an folder called "app-builds"

**Comment by Minenash** [comment]
I've never touched Wine's config; I thought the default would of been 7 xD
Well changing that didn't work, but using your release worked, so thank you very much, an application like this is awesome to have.

Not sure where exactly to put this question so I'll just add it to this: @Stevertus do you plan on adding categories or a search box? Seems like loading every datapack would be a waste of resources, and hard to find the one you want, once this gets more packs.

**Comment by Stevertus** [comment]
@Minenash Yeah an update is already in the making. My packager was a bit bugged, so an official version for Linux should also follow.

**Pull request closed without merging**
